### ISSUE TITLE
Příliš mnoho zamítnutých transakcí

### ISSUE THREAD

**Issue by LIPdistribution** [csob/posmerchantapi#1]
Hezký den do ČSOB,

chtěl bych vás požádat o radu a případně i o technickou pomoc .
U ČSOB využíváme čtyři multiměnové brány, každá náleží jednomu našemu eshopu,
kde ji využíváme vždy na pěti národních doménách.

M1MIPS0366	MEGAskate.cz /.de /.pl /.eu /.sk
M1MIPS0368	TempleStore.cz /.de /.pl /.eu /.sk
M1MIPS1437	ESATNA.cz /.de /.pl /.eu /.sk
M1MIPS1438	SWIS-SHOP.cz /.de /.pl /.com /.sk
 
M1MIPS0367	TempleStore.sk - již mimo provoz

Bohužel evidujeme veliký výskyt na první pokus neprovedených plateb, kdy i zákazníci nás upozorňují na to,
že se jim nedaří zaplatit a chtějí změnit platbu na převodním příkazem, že máme chybu na stránkách.

Udělali jsme analýzu transakcí a v příloze je vidět, že jich je opravdu hodně.
Žlutě jsou transakce, které zákazník na druhý/třetí pokus zaplatil a červeně jsou nikdy nezaplacené.
Přicházíme tedy jak my, tak vy o tržbu.

Dala by se zjistit nějaká podrobnější příčina tohoto stavu?
Třeba proč Platební metoda = Neznámý - co bylo přímým důvodem zamítnutí platby?

Využíváme pět měn a zamítnutí jsou napříč měnami i bránami, přímou souvislost nikde nevidím.

Bohužel nám to zatěžuje Zákaznický servis, kdy před Vánocemi bychom měli řešit jiné starosti :-)

Předem moc děkuji za pomoc při hledání příčiny této abnormality.

Přeji krásný den
Jiří Bůbal
tel. +420.777.788.798
jiri.bubal@templestore.cz

**Comment by LIPdistribution** [comment]
V tom našem logu je dost často druhý pokus o zaplacení 0s-1s po prvním pokusu,
přitom tam nevidím žádné zamítnutí. Volá se return.php a asi to ČSOB volá 2x po sobě?
Nebo se nepodařilo spojit / přenést data atd. - chybu v logu nevidím, ale nepředpokládám, že by zákazník klikl po vteřině sám na opakování platby.

**Comment by mrazekl** [comment]
Dobrý den,
prověříme a se zjištěnými fakty vás budeme informovat. Nicméně bych doporučoval odstranit přiložený výpis, jedná se totiž o citlivé informace, které jste veřejně vystavil.
Také jste dotaz založil ve špatné kategorii, do budoucna prosím zakládejte ve 
https://github.com/csob/paymentgateway/issues

**Comment by LIPdistribution** [comment]
Omlouvám se, odstraněno. 
Když jsem zakládal GitHub, abych toto mohl poslat, tak jsem si vybral "soukromé nastavení" a myslel jsem si, že je to pouze komunikace mezi mnou a ČSOB. Příště použiju správný issue. 
Moc děkuji

**Comment by mrazekl** [comment]
Dobrý den,
popravdě si nejsem úplně jist, kdo všechno má přístup do tohoto typu issue, ale jak se říká, bezpečnost především.
Na vaši emailovou adresu jsem zaslal analýzu, pokud nejste proti, tohle issue bych uzavřel a případné další otázky vyřešíme via e-mail. Přece jen se jedná o váš kontkrétní případ, který by jiným uživatelům ČSOB gateway nebyl k užitku.
